# Generated by Django 5.2.5 on 2025-08-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='section',
            field=models.CharField(choices=[('barista', 'باريستا'), ('buffet', 'بوفيه')], default='buffet', max_length=20),
        ),
    ]
