# Generated by Django 5.2.5 on 2025-08-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_orderitem_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='section',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='section',
            field=models.CharField(choices=[('barista', 'باريستا'), ('buffet', 'بوفيه')], default='buffet', max_length=20),
        ),
    ]
