# Generated by Django 5.2.5 on 2025-08-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order_cashier'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
