# Generated by Django 5.2.5 on 2025-09-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='show_in_qeta3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='section',
            field=models.CharField(choices=[('barista', 'باريستا'), ('buffet', 'بوفيه'), ('canteen', 'كانتين')], default='buffet', max_length=20),
        ),
    ]
