# Generated by Django 5.2.5 on 2025-09-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_menuitem_show_in_qeta3_alter_menuitem_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('cafe', 'Cafe'), ('takeaway', 'Takeaway'), ('qeta3', 'Qeta3')], max_length=20),
        ),
    ]
