# Generated by Django 5.2.5 on 2025-09-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_officer_order_officer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='section',
            field=models.CharField(choices=[('barista', 'باريستا'), ('buffet', 'بوفيه'), ('canteen', 'كانتين'), ('addons', 'إضافات')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sinastarinventory',
            name='type',
            field=models.CharField(choices=[('Canteen', 'Canteen'), ('Buffet', 'Buffet'), ('Baresta', 'Baresta')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='sinastarinventory',
            unique_together={('material', 'type')},
        ),
    ]
