# Generated by Django 5.2.5 on 2025-09-07 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_menuitem_section_alter_sinastarinventory_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sinastarinventory',
            unique_together=set(),
        ),
    ]
