# Generated by Django 5.2.5 on 2025-09-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_sinastarinventory_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinastarinventory',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
