# Generated by Django 5.2.5 on 2025-09-07 20:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_sinastarinventory_purchase_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(default=django.utils.timezone.now)),
                ('profit_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('profit_expected', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('profit_remaining', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
