# Generated by Django 5.2.5 on 2025-09-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_monthlyclosing'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyclosing',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='monthlyclosing',
            name='month',
            field=models.DateField(),
        ),
    ]
