# Generated by Django 5.2.5 on 2025-09-07 22:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_monthlyclosing_total_cost_alter_monthlyclosing_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinastarinventory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sinastarinventory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
