# Generated by Django 5.2.5 on 2025-09-07 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_sinastarinventoryhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyclosing',
            old_name='profit_actual',
            new_name='actual_profit',
        ),
        migrations.RenameField(
            model_name='monthlyclosing',
            old_name='profit_expected',
            new_name='profit_from_inventory',
        ),
        migrations.RenameField(
            model_name='monthlyclosing',
            old_name='profit_remaining',
            new_name='total_profit',
        ),
        migrations.RenameField(
            model_name='monthlyclosing',
            old_name='total_cost',
            new_name='total_purchase_inventory',
        ),
        migrations.AddField(
            model_name='monthlyclosing',
            name='total_sales_inventory',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='monthlyclosing',
            name='total_sales_orders',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
