# Generated by Django 5.2.5 on 2025-09-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_soldmaterialhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyclosing',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlyclosing',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
