# Generated by Django 5.2.5 on 2025-09-08 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_order_grand_total_order_items_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='grand_total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items_total',
        ),
    ]
