# Generated by Django 5.2.5 on 2025-09-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_order_grand_total_remove_order_items_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('drink', 'Drink'), ('7alak', '7alak'), ('shesha', 'shesha')], default='food', max_length=50),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='section',
            field=models.CharField(choices=[('barista', 'باريستا'), ('mat3am', 'مطعم'), ('canteen', 'كانتين'), ('7alak', '7alak'), ('shesha', 'shesha'), ('addons', 'إضافات')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('barista', 'باريستا'), ('mat3am', 'مطعم'), ('waiter', 'ويتر'), ('admin', 'أدمن'), ('7alak', 'حلاق'), ('shesha', 'شيشة')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sinastarinventory',
            name='type',
            field=models.CharField(choices=[('Canteen', 'Canteen'), ('mat3am', 'mat3am'), ('Baresta', 'Baresta'), ('7alak', '7alak'), ('shesha', 'shesha')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sinastarinventoryhistory',
            name='type',
            field=models.CharField(choices=[('Canteen', 'Canteen'), ('mat3am', 'mat3am'), ('Baresta', 'Baresta'), ('7alak', '7alak'), ('shesha', 'shesha')], max_length=20),
        ),
        migrations.AlterField(
            model_name='soldmaterialhistory',
            name='type',
            field=models.CharField(choices=[('Canteen', 'Canteen'), ('mat3am', 'mat3am'), ('Baresta', 'Baresta'), ('7alak', '7alak'), ('shesha', 'shesha')], max_length=20),
        ),
    ]
