# Generated by Django 5.2.5 on 2025-09-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_menuitem_category_alter_menuitem_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinastarinventory',
            name='total_purchase_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
