# Generated by Django 5.2.5 on 2025-09-11 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_sinastarinventory_total_purchase_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinastarinventoryhistory',
            name='total_purchase_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
