# Generated by Django 5.2.5 on 2025-09-11 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_sinastarinventoryhistory_total_purchase_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='materialhistory',
            name='cost',
        ),
    ]
