# Generated by Django 5.2.5 on 2025-09-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_material_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='materialhistory',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sinastarinventory',
            name='addition',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sinastarinventory',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sinastarinventoryhistory',
            name='addition',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sinastarinventoryhistory',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='soldmaterialhistory',
            name='addition',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='soldmaterialhistory',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
