# Generated by Django 5.2.5 on 2025-09-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_material_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinastarinventory',
            name='addition_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sinastarinventory',
            name='purchase_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
