# Generated by Django 5.2.5 on 2025-09-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_sinastarinventory_addition_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinastarinventory',
            name='addition_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sinastarinventory',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
