# Generated by Django 5.2.5 on 2025-09-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_sinastarinventory_addition_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('nesrayat', 'نسريات'), ('tips', 'تبس')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
