# Generated by Django 5.2.5 on 2025-09-17 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_extraexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyclosing',
            name='total_nesrayat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='monthlyclosing',
            name='total_tips',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
