# Generated by Django 5.2.5 on 2025-09-17 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_monthlyclosing_total_nesrayat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinastarinventory',
            name='total_purchase_value',
        ),
    ]
