# Generated by Django 5.2.5 on 2025-10-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_remove_sinastarinventory_total_purchase_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=0.1, help_text='اكتب النسبة كقيمة عشرية (مثال: 0.10 = 10%, 0.50 = 50%)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='officer',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
