# Generated by Django 5.2.5 on 2025-10-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_officer_discount_rate_alter_officer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'كاش'), ('vodafone', 'فودافون كاش'), ('moagel', 'مؤجل')], max_length=20, null=True),
        ),
    ]
