# Generated by Django 5.2.5 on 2025-10-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_order_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinastarinventory',
            name='minimum_stock',
            field=models.IntegerField(default=0, help_text='الحد الأدنى قبل التنبيه'),
        ),
    ]
